codecov:
  branch: develop
coverage:
  round: nearest
  status:
    project:
      default:
        # basic
        target: 75%
        threshold: 0%
        base: auto
        paths:
          - "src"
parsers:
  jacoco:
    partials_as_hits: true