name: CodeCov Coverage Collection

on:
  push:
    branches:
      - "develop"

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3