name: CodeCov Coverage Collection

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/connect-page"
      - "feature/notifications-page"
      - "feature/attributes-page"
      - "feature/attribute-phrase-review"
      - "feature/attributes-page-temp"
      - "feature/review-attributes-page"

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3